### ISSUE TITLE
On calculating the negative logarithm of the likelihood

### ISSUE THREAD

**Issue by yuanzunli** [gkulkarni/QLF#1]
@gkulkarni Dear Dr. Kulkarni, I‘m not clear how did you calculate the double integral term  of the negative logarithm of the likelihood (Equation 10 in your paper). From the "individual.py" file, I can see the code:

```python
    def neglnlike(self, theta):

        logphi = self.log10phi(theta, self.M1450) # Mpc^-3 mag^-1
        logphi /= np.log10(np.e) # Convert to base e 

        return -2.0*logphi.sum() + 2.0*self.lfnorm(theta)
```
Obviously, you calculated the double integral term as self.lfnorm(theta), 
```python
    def lfnorm(self, theta):

        ns = np.array([x.nqso(self, theta) for x in self.maps])
        return sum(ns) 
```
but not using the scipy.integrate module 'dblquad'. Could you please explain the process in more detail?

**Comment by yuanzunli** [comment]
I think I have found the answer. The selection function is not continuous and is given as a grid with small sizes of dM1450 and dz.
Considering the small sizes, You  used a simple sum of the p(M1450,z) to calculate equation (10).

**Comment by gkulkarni** [comment]
Hi @yuanzunli, the double integral is computed using the `selmap.nqso` method. So you are right: we are simply summing over the tiles instead of using something like `dblquad`. (See comment in our paper in the paragraph following Equation 6.) But the reason we do this is not that the tiles are small -- they actually not small in some cases -- but because this is an unambiguous way of computing the integral. Our thinking is that the person who computes the completeness map should make sure that the computation is tabulated on tiles that are small enough for convergence. If we use fancier integration algorithms for a given completeness map, there is a risk that the computed integral value will differ from person to person to do the algorithmic error. In this sense, summing over the tiles is the best that we can do. Hope this helps.
